config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Main Pages
  root 'landing#index'
  get 'landing/index'
  get 'activity/index'

  # My Request and Request Details
  get '/request_preview_card/:request_id', :to => "request_preview_card#index", :as => 'request_preview_card'

  get 'my_requests_questions/index'
  get 'my_requests_answers/index'
  get 'my_requests_favorited/index'
  get 'my_requests_starred/index'

  post "my_requests_favorited/:request_id", :to => "my_requests_favorited#create", :as => 'my_requests_favorited'

  post "my_requests_starred/:request_id", :to => "my_requests_starred#create", :as => 'my_requests_starred'

  get '/request_details/index/:id', :to => 'request_details#index', :as => 'request_details'

  post "/request_details/onCreateComment/:request_id", :to=> "request_details#onCreateComment", :as => "onCreateComment"

  # Request Advice
  resources :request_advice, only: [] do
    collection do
      get 'index'
      post 'onSubmitQuestion'
      post 'onSubmitAdvice'
    end
  end

  # User Account Management
  resources :login, only: [] do
    collection do
      get 'index'
      post 'onLogin'
      post 'onSignup'
    end
  end

  resources :settings, only: [] do
    collection do
      get 'index'
      post 'onUserUpdate'
    end
  end

  get '/logout',  to: 'login#onLogout'


  # Footer
  get 'about/index'
  get 'terms_of_service/index'
  get 'privacy_policy/index'

  get '/google3e09508c655584f0', :to => redirect('/google3e09508c655584f0.html')

end

app/controllers/request_advice_controller.rb
class RequestAdviceController < ApplicationController

  def index
    if currentUser.nil?
      flash[:notice] = "Please log in first before requesting an advice"
      redirect_to(login_index_path)
      return
    end

    # Match user with a question to be answered.
    # Not the question asked by the user themself
    matchRequest = Request.where(:answerUserId => nil).where.not(:askUserId=>currentUser.id).limit(50).sample

    if matchRequest.nil?
      return
    end

    matchUser = User.find_by(:id => matchRequest[:askUserId])

    # Setup instance variables for view
    @matchUserName = matchUser.nickName
    @matchUserId = matchUser.id
    @matchRequestId = matchRequest.id

    @matchReqeustTitle = matchRequest.title
    @matchReqeustDetails = matchRequest.details
    @matchRequestAskTime = matchRequest.askTime.strftime("%B %d, %Y")

  end

  def onSubmitQuestion

    if currentUser.nil?
      flash[:notice] = "Please log in first before requesting an advice"
      redirect_to(login_index_path)
      return
    end

    # if !verify_recaptcha
    #   redirect_to(request_advice_index_path)
    #   return
    # end

    requestQuestion = params["request_question"]
    requestAdvice = params["request_advice"]
    @matchUserName = params["matchUserName"]
    matchUserId = params["matchUserId"]
    matchRequestId = params["matchRequestId"]

    rawQuestionTitle = requestQuestion["title"]
    rawQuestionDetails = requestQuestion["details"]
    @questionIsPublic = requestQuestion["isPublic"]

    # Submition filtering
    #----------------------
    if rawQuestionTitle.nil? ||
      rawQuestionTitle.length < 2 ||
      rawQuestionTitle.length > 250
      flash[:notice] = "Error Saving: Question title must be 2 to 250 characters"
      redirect_back(fallback_location: request_advice_index_path)
      return
    end

    @questionTitle = rawQuestionTitle

    @questionDetails = rawQuestionDetails.truncate(5000, " ")

    if (requestAdvice.nil? || requestAdvice["answer"].nil?) && !@matchUserId.nil?
      flash[:notice] = "Error Saving: Advice must not be empty"
      redirect_back(fallback_location: request_advice_index_path)
      return
    end

    @adviceAnswer = ""
    if !requestAdvice.nil? && !requestAdvice["answer"].nil?
      @adviceAnswer = requestAdvice["answer"]
    end

    # Set other instance variables
    @questionIsPublicString = "Private Question. No one other than matched users can see this request."
    if @questionIsPublic == 1
      @questionIsPublicString = "Public Question. Is viewable by anyone."
    end

    # Creating a new request for the current user
    newRequest = Request.new
    newRequest.title = @questionTitle
    newRequest.details = @questionDetails
    newRequest.isPublic = @questionIsPublic
    newRequest.askTime = Time.now
    newRequest.askUserId = currentUser.id
    # Request is only saved AFTER advice is successfully saved

    @questionAskTime = newRequest.askTime

    # For error tracking
    saveSuccess = true
    appendedToAnswer = false

    # Adding current user's advice to the matched user's request
    matchRequest = Request.find_by(:id => matchRequestId)

    # If there is matched request for user, save the request after advice is given.
    # If no match is given to user, save the question directly
    if !matchRequest.nil?

      if @adviceAnswer.length >= 2 && @adviceAnswer.length <= 5000
        if matchRequest.answer.nil?
          appendedToAnswer = false

          matchRequest.answer = @adviceAnswer.truncate(5000, separator: ' ')
          matchRequest.answerTime = Time.now
          matchRequest.answerUserId = currentUser.id
        else
          appendedToAnswer = true

          matchRequest.answer = matchRequest.answer + "                                                         " + "(#{currentUser.nickName} gave another answer) --> " + @adviceAnswer.truncate(5000, separator: ' ')
        end

        if !newRequest.save
          saveSuccess = false
        end

        if !matchRequest.save
          saveSuccess = false
        end
      else
        flash[:notice] = "Error Saving: Advice must be 2 to 5000 characters"
        redirect_back(fallback_location: request_advice_index_path)
        return
      end

    else # if no matched request, save the question directly
      if !newRequest.save
        saveSuccess = false
      end
    end

    # Get id only after saving successfully
    @questionId = newRequest.id

    if saveSuccess
      if appendedToAnswer
        flash[:notice] = "Request Success! Someone gave an advice to the question you were answering. Your advice is added but won't be visible under My Requests"
      else
        flash[:notice] = "Request Submitted Successfully"
      end
      return
    else
      flash[:notice] = "Error Saving: #{newRequest.errors.full_messages}"
      redirect_back(fallback_location: request_advice_index_path)
      return
    end
  end


end

app/helpers/request_advice_helper.rb
module RequestAdviceHelper
end

app/views/request_advice/index.html.erb
<div class="container">

  <div class="row header">
    <div>
      <% heart_filled_src = "icons/icon-donna2.png" %>
      <%= image_tag(heart_filled_src, class: "donna_icon", size:"40x40", alt:"donna icon", style:"margin-top:10px;margin-bottom:-10px;") %>
      <h4 style="display: inline;">Request Advice</h4>
    </div>
    <div class="divider"></div>
  </div>

  <div class="row">

    <%= form_for :request_question, :id=>"request_form", :url=>onSubmitQuestion_request_advice_index_path do |f| %>

    <div class="col s12 l6">
      <div>
        <h5>Step 1: Your Question</h5>
        <div class="divider"></div>
        <br />

        <div class="input-field">
          <%= f.text_field :title, :id=>"question_title", :placeholder=>"Your question title goes here (10-255 characters)", :type=>"text", :id=>"title", :html => {'data-length'=>"255"} %>
          <%= f.label "Question Title", :for => :title %>
        </div>

        <div class="input-field">
          <%= f.text_area :details, :placeholder=>"Details of your question goes here (5000 characters max)", :id=>"details", :class=>"materialize-textarea" %>
          <%= f.label "Question Details", :for => :details %>
        </div>

        <div>
          <%= f.check_box :isPublic, :id=>"isPublic" %>
          <%= f.label "Make my request public", :for => :isPublic %>
        </div>

        <!-- <br />
        <%= recaptcha_tags %> -->

      </div>
      <br />
      <br />

    </div>

    <div class="row">
      <div class="col s12 l6">
        <h5>Step 2: Give <%=@matchUserName%> an Advice</h5>
        <div class="divider"></div>
        <br />

        <% if @matchUserName.nil? %>
          <p>Normally you are matched with another person, but there are no matches found at this time. You can directly submit your question.</p>
          <br />
        <% else %>
          <div class="card teal darken-1">
            <div class="card-content white-text">
              <inline><%=@matchUserName%> asked on </inline>
              <inline><%=@matchRequestAskTime%></inline>
              <div>
                <span class="card-title" style="font-family: 'Courgette', sans-serif"><%=@matchReqeustTitle%></span>
                <p><%=@matchReqeustDetails%></p>
                <br />
                <p style="font-family: 'Courgette', sans-serif">
                  Sincerely,<br />
                  <%=@matchUserName%>
                </p>
              </div>
            </div>
          </div>

          <%= hidden_field_tag :matchRequestId, "#{@matchRequestId}" %>
          <%= hidden_field_tag :matchUserId, "#{@matchUserId}" %>
          <%= hidden_field_tag :matchUserName, "#{@matchUserName}" %>

          <%= fields_for :request_advice do |advice_field| %>

            <%= advice_field.label "Your Perspective and Advice", :for=>:answer %>
            <%= advice_field.text_area :answer, :id=>"advice_field", :class=>"materialize-textarea", :placeholder => "Please give your advice here (2 to 5000 characters)" %>

          <% end %> <!-- end of fields_for -->

         <% end %> <!-- end of if @matchUserName.nil? statement -->
      </div>

    </div>

    <div class="row center">
      <span class="btn-large waves-effect waves-light orange"><%= f.submit "Submit Request", :id=>"submit_button"%></span>
    </div>

    <% end %>

  </div>

  <br />

</div>

<script type="text/javascript">
  mixpanel.track("request_advice_viewed", {
      "user_id": 000,
  });
</script>

app/views/request_advice/onSubmitQuestion.html.erb
<div class="container">

  <div class="row header">
    <h4>Request Submitted</h4>
    <div class="divider"></div>
    <br />
  </div>

  <%= link_to(request_details_path(@questionId)) do %>
    <div class="card teal darken-3">
      <div class="card-content white-text">
        <b>You asked on </b>
        <b><%= @questionAskTime.strftime("%B %d, %Y") %></b>
        <div style="font-family: 'Courgette', sans-serif">
          <span class="card-title"><%= @questionTitle %></span>
          <div class="divider"></div>
          <p><%= @questionDetails %></p>
        </div>
      </div>
    </div>
  <% end %>

  <div class="center">
    <p class="center-align teal-text">You can view all of your requests by going back to My Requests</p>
    <div class="btn-large waves-effect waves-light orange">
      <%= button_to "My Requests", my_requests_questions_index_path, :method => :get %>
    </div>
  </div>

</div>

<script type="text/javascript">
  mixpanel.track("onSubmitQuestion_viewed", {
      "user_id": 000,
  });
</script>