config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Main Pages
  root 'landing#index'
  get 'landing/index'
  get 'activity/index'

  # My Request and Request Details
  get '/request_preview_card/:request_id', :to => "request_preview_card#index", :as => 'request_preview_card'

  get 'my_requests_questions/index'
  get 'my_requests_answers/index'
  get 'my_requests_favorited/index'
  get 'my_requests_starred/index'

  post "my_requests_favorited/:request_id", :to => "my_requests_favorited#create", :as => 'my_requests_favorited'

  post "my_requests_starred/:request_id", :to => "my_requests_starred#create", :as => 'my_requests_starred'

  get '/request_details/index/:id', :to => 'request_details#index', :as => 'request_details'

  post "/request_details/onCreateComment/:request_id", :to=> "request_details#onCreateComment", :as => "onCreateComment"

  # Request Advice
  resources :request_advice, only: [] do
    collection do
      get 'index'
      post 'onSubmitQuestion'
      post 'onSubmitAdvice'
    end
  end

  # User Account Management
  resources :login, only: [] do
    collection do
      get 'index'
      post 'onLogin'
      post 'onSignup'
    end
  end

  resources :settings, only: [] do
    collection do
      get 'index'
      post 'onUserUpdate'
    end
  end

  get '/logout',  to: 'login#onLogout'


  # Footer
  get 'about/index'
  get 'terms_of_service/index'
  get 'privacy_policy/index'

  get '/google3e09508c655584f0', :to => redirect('/google3e09508c655584f0.html')

end

app/helpers/my_answers_helper.rb
module MyAnswersHelper
end

app/views/my_answers/index.html.erb
<div class="container">
  <h4>My Answers</h4>
  <div class="divider"></div>
  <br />

  <% if @requests.length == 0 %>
    <div class="center">
      <br />
      <h3 class="center-align grey-text"><i class="large material-icons">create</i></h3>
      <h5 class="center-align grey-text">You haven't given any advices yet. Try giving your first advice while making a personal request.</h5>
      <br />
      <div class="btn-large waves-effect waves-light orange">
        <%= button_to "Request Advice", request_advice_index_path, :method => :get %>
      </div>

      <br />
      <br />
    </div>
  <% end %>


  <% @requests.length.times do |i| %>
    <% req = @requests[i] %>
    <% askUserName = @askUserNames[i] %>
    <%= link_to(request_details_path(req.id)) do %>
      <div class="card teal lighten-5">
        <div class="card-content black-text">
          <b><%= "#{askUserName} asked on " %></b>
          <b><%= req.askTime.strftime("%B %d, %Y") %></b>
          <span class="card-title">
            <%=req.title%>
          </span>
          <p><%= req.details %></p>
        </div>
      </div>
      <% end %>
  <% end %>
</div>

<script type="text/javascript">
  mixpanel.track("my_answers_viewed", {
      "user_id": 000,
  });
</script>